"""Generated by craig-ai-tooling/axi-py vendor.py. Do not edit; rerun `make vendor-axi`.

palette_axi/axi.py is a vendored copy of the output and exit-code contract every Python AXI
shares. An edit made here is how the tools drift apart, so this test fails on one.
Change it upstream in craig-ai-tooling/axi-py, tag it, then run
`make vendor-axi AXI_PY_REF=<tag>` in this repo.
"""
import hashlib
import pathlib
import re
import unittest

AXI = pathlib.Path(__file__).resolve().parent.parent / "palette_axi" / "axi.py"
HEADER = re.compile(rb"# VENDORED from craig-ai-tooling/axi-py (v[0-9]+\.[0-9]+\.[0-9]+) sha256=([0-9a-f]{64})\n")


class VendoredAxiIsUnedited(unittest.TestCase):
    def setUp(self):
        self.raw = AXI.read_bytes()
        self.header = HEADER.match(self.raw)
        self.assertIsNotNone(self.header, f"{AXI} has no release header; run `make vendor-axi`")

    def test_body_matches_the_hash_in_its_header(self):
        body = self.raw.split(b"\n", 2)[2]
        self.assertEqual(
            hashlib.sha256(body).hexdigest(), self.header.group(2).decode(),
            f"{AXI} was edited in place. Revert it, make the change in craig-ai-tooling/axi-py, "
            "tag it, then `make vendor-axi AXI_PY_REF=<tag>`.")

    def test_header_names_the_version_the_body_declares(self):
        version = re.search(rb'^__version__ = "([^"]+)"$', self.raw, re.M)
        self.assertIsNotNone(version, f"{AXI} declares no __version__")
        self.assertEqual(b"v" + version.group(1), self.header.group(1))


if __name__ == "__main__":
    unittest.main()
